[package]
name = "rust2genshin"
version.workspace = true
authors.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]
enum_dispatch = { workspace = true }
downcast = { workspace = true }
anyhow = { workspace = true }
clap = { version = "4", features = ["derive"] }
prost = "0"
serde_json = "1"

[build-dependencies]
prost-build = "0"
