[package]
name = "rust2genshin"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true

[lib]
path = "src/lib.rs"
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "rust2genshin-linker"
path = "src/linker.rs"

[lints]
workspace = true

[dependencies]
tap = { workspace = true }
either = { workspace = true, features = ["serde"] }
downcast = { workspace = true }
serde = { workspace = true }
typetag = { workspace = true }
bincode = { version = "2", features = ["serde"] }
ar = "0"
prost = "0"
syn = "3"
proc-macro2 = "1"
slab = { version = "0", features = ["serde"] }

[build-dependencies]
prost-build = "0"
