[package]
name = "rust2genshin-lib"
version.workspace = true
edition.workspace = true
authors.workspace = true
rust-version.workspace = true

[dependencies]
rust2genshin-lib-internal = { path = "../lib-internal" }

#[lib]
#crate-type = ["staticlib"]

[features]
server = []

[lints]
workspace = true
