[package]
name = "build-demo"
version.workspace = true
edition.workspace = true
authors.workspace = true

[[bin]]
name = "beyond-server"
path = "src/beyond-server.rs"

[[bin]]
name = "classic-server"
path = "src/classic-server.rs"

[dependencies]
new_string_template = "1"
serde_json = "1"

[lints]
workspace = true
