[package]
name = "rust2genshin-demo"
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
#homepage.workspace = true
#license.workspace = true
#repository.workspace = true
#version.workspace = true

[lints]
workspace = true

[dependencies]
rust2genshin-lib = { workspace = true }
rand = "0.10.2"
