name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup Protoc
      run: sudo apt install protobuf-compiler
    - name: Build
      run: cargo run -p build-demo
    - name: Upload
      uses: actions/upload-artifact@v7
      with:
        path: |
          target/rust2genshin_demo.gia
        archive: false
        if-no-files-found: error
